---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
    css: "ReportDashboardStyles.css"
editor_options: 
  chunk_output_type: console
---

Calibration {data-navmenu="Firm Synthesis Model"}
============================================

firm_sim_taz_land_use {data-width=400 .tabset}
--------------------------------------------

**Firm Synthesis Model: Calibration Summaries**

Firm synthesis output comparisons with input and control data.

- firm_sim_taz_land_use processes land use inputs and prepares a database for use in later steps of the model. Calibration checks are confirmatory to ensure that the databse matches the input data.
- firm_sim_scale_employees scales the synthesized establishment list to match TAZ employment totals by industry. Calibration checks are confirmatory to ensure that the employment totals are matched.

### firm_sim_taz_land_use: Industry

```{r Chart_firm_sim_taz_land_use_industry}
# Organize
dat <- cal_results$firm_sim_taz_land_use$submodel_comparison[!Category %in% c("HH", "NEmp_Total"), .(Model = sum(Model), Target = sum(Target)), keyby = .(Industry = Category)]

dat <- melt.data.table(dat, id.vars = "Industry", variable.name = "Source", value.name = "Employment")
dat[, Industry := sub("NEmp_", "", Industry)]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_taz_land_use_industry.csv"))
assign("db_tab_firm_sim_taz_land_use_industry", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "Industry", yvar = "Employment",  fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_taz_land_use_industry.png")

```

### firm_sim_taz_land_use: Employment by District

```{r Chart_firm_sim_taz_land_use_emp_District}
# Organize
dat <- cal_results$firm_sim_taz_land_use$submodel_comparison[Category %in% c("NEmp_Total"), .(Model = sum(Model), Target = sum(Target)), keyby = .(District = SummaryGeog)]

dat <- melt.data.table(dat, id.vars = "District", variable.name = "Source", value.name = "Employment")
dat[, District := factor(District, levels = levels(TAZ_System$DistrictName))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_taz_land_use_emp_district.csv"))
assign("db_tab_firm_sim_taz_land_use_emp_district", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "District", yvar = "Employment", fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_taz_land_use_emp_district.png")

```

### firm_sim_taz_land_use: Households by District

```{r Chart_firm_sim_taz_land_use_hh_District}
# Organize
dat <- cal_results$firm_sim_taz_land_use$submodel_comparison[Category %in% c("HH"), .(Model = sum(Model), Target = sum(Target)), keyby = .(District = SummaryGeog)]

dat <- melt.data.table(dat, id.vars = "District", variable.name = "Source", value.name = "Households")
dat[, District := factor(District, levels = levels(TAZ_System$DistrictName))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_taz_land_use_hh_district.csv"))
assign("db_tab_firm_sim_taz_land_use_hh_district", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "District", yvar = "Households", fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_taz_land_use_hh_district.png")

```

firm_sim_scale_employees {data-width=400 .tabset}
--------------------------------------------

### firm_sim_scale_employees: Industry

```{r Chart_firm_sim_scale_employees_industry}
# Organize
dat <- cal_results$firm_sim_scale_employees$submodel_comparison[, .(Model = sum(Model), Target = sum(Target)), keyby = .(Industry = CatLabel)]

dat <- melt.data.table(dat, id.vars = "Industry", variable.name = "Source", value.name = "Employment")

# Shorten long label
dat[Industry == "Administrative and Support and Waste Management and Remediation Services",
    Industry := "Admin, Support, Waste Man, Remediation Services"]
                 
# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_scale_employees_industry.csv"))
assign("db_tab_firm_sim_scale_employees_industry", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "Industry", yvar = "Employment",  fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_scale_employees_industry.png")

```

### firm_sim_scale_employees: Employment by District

```{r Chart_firm_sim_scale_employees_District}
# Organize
dat <- cal_results$firm_sim_scale_employees$submodel_comparison[, .(Model = sum(Model), Target = sum(Target)), keyby = .(District = SummaryGeog)]

dat <- melt.data.table(dat, id.vars = "District", variable.name = "Source", value.name = "Employment")
dat[, District := factor(District, levels = levels(TAZ_System$DistrictName))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_scale_employees_district.csv"))
assign("db_tab_firm_sim_scale_employees_district", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "District", yvar = "Employment", fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_scale_employees_district.png")

```
