---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
    css: "ReportDashboardStyles.css"
editor_options: 
  chunk_output_type: console
---
Comparison {data-navmenu="Trip Tables"}
============================================

Highlights {data-width=150}
--------------------------------------------

**Trip Tables: Comparison with Reference Scenario**

Daily trip table summaries, comparing trip table characteristics such as county to county OD patterns between the current scenario and the reference scenario.

Scenarios being compared:

- the current scenario is **`r SCENARIO_NAME`**
- the reference scenario is **`r SCENARIO_REFERENCE_NAME`**

Column {data-width=600, .tabset}
--------------------------------------------

### County Origins (All Vehicles) 

```{r Chart_tt_val_county_origins}
# Organize
dat_scen <- TripTable[, .(ScenTrips = sum(trips, na.rm = TRUE)), keyby = .(OriginCounty = OSummaryGeog)]
dat_scen[, Scenario := ScenTrips/sum(ScenTrips)]

dat_ref <- ref_TripTable[, .(RefTrips = sum(trips, na.rm = TRUE)), keyby = .(OriginCounty = OSummaryGeog)]
dat_ref[, Reference := RefTrips/sum(RefTrips)]


dat <- merge(dat_ref, dat_scen, by= "OriginCounty", all = TRUE)
dat[is.na(Reference), Reference := 0]
dat[is.na(Scenario), Scenario := 0]

dat[, Difference := Scenario - Reference]
dat[, Ratio := ifelse(Reference != 0, Scenario/Reference, 0)]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "tt_build_county_origins_all.csv"))
assign("db_tab_tt_build_county_origins_all", dat, envir = db_inputs)

# Table
kable(dat[,.(OriginCounty, Reference, Scenario, Difference, Ratio)], escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed")) 

```


### County Destinations (All Vehicles) 

```{r Chart_tt_val_county_dest}
# Organize
dat_scen <- TripTable[, .(ScenTrips = sum(trips, na.rm = TRUE)), keyby = .(DestinationCounty = DSummaryGeog)]
dat_scen[, Scenario := ScenTrips/sum(ScenTrips)]

dat_ref <- ref_TripTable[, .(RefTrips = sum(trips, na.rm = TRUE)), keyby = .(DestinationCounty = DSummaryGeog)]
dat_ref[, Reference := RefTrips/sum(RefTrips)]

dat <- merge(dat_ref, dat_scen, by= "DestinationCounty", all = TRUE)
dat[is.na(Reference), Reference := 0]
dat[is.na(Scenario), Scenario := 0]

dat[, Difference := Scenario - Reference]
dat[, Ratio := ifelse(Reference != 0, Scenario/Reference, 0)]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "tt_build_county_dest_all.csv"))
assign("db_tab_tt_build_county_origins_all", dat, envir = db_inputs)

# Table
kable(dat[,.(DestinationCounty, Reference, Scenario, Difference, Ratio)], escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed")) 

```

### County Origins (Light Vehicles) 

```{r Chart_tt_val_county_origins_light}
# Organize
dat_scen <- TripTable[, .(ScenTrips = sum(trips, na.rm = TRUE)), keyby = .(OriginCounty = OSummaryGeog, Vehicle)]
dat_scen[, Scenario := ScenTrips/sum(ScenTrips), by = Vehicle]

dat_ref <- ref_TripTable[, .(RefTrips = sum(trips, na.rm = TRUE)), keyby = .(OriginCounty = OSummaryGeog, Vehicle)]
dat_ref[, Reference := RefTrips/sum(RefTrips), by = Vehicle]


dat <- merge(dat_ref, dat_scen, by= c("OriginCounty", "Vehicle"), all = TRUE)
dat[is.na(Reference), Reference := 0]
dat[is.na(Scenario), Scenario := 0]

dat[, Difference := Scenario - Reference]
dat[, Ratio := ifelse(Reference != 0, Scenario/Reference, 0)]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "tt_build_county_origins_vehicle.csv"))
assign("db_tab_tt_build_county_origins_vehicle", dat, envir = db_inputs)

# Table
kable(dat[Vehicle == "Light",.(OriginCounty, Reference, Scenario, Difference, Ratio)], escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed")) 

```

### County Origins (Medium Trucks) 

```{r Chart_tt_val_county_origins_medium}
# Table
kable(dat[Vehicle == "Medium",.(OriginCounty, Reference, Scenario, Difference, Ratio)], escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed")) 

```

### County Origins (Heavy Trucks) 

```{r Chart_tt_val_county_origins_heavy}
# Table
kable(dat[Vehicle == "Heavy",.(OriginCounty, Reference, Scenario, Difference, Ratio)], escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed")) 

```


### Percent Trips by County OD: Scenario

```{r Chart_Percent_Trips_By_County_OD_scen}
# Organize
dat_scen <- TripTable[, .(ScenTrips = sum(trips, na.rm = TRUE)), by = .(OriginCounty = OSummaryGeog, DestinationCounty = DSummaryGeog)]
dat_scen[, Scenario := ScenTrips/sum(ScenTrips)]
dat <- add_totals(dcast.data.table(dat_scen,
                                  OriginCounty ~ DestinationCounty,
                                   fun.aggregate = sum,
                                   value.var = "Scenario"))

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "tt_build_county_od_scen.csv"))
assign("db_tab_tt_build_county_od_scen", dat, envir = db_inputs)

# Table
kable(dat, escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed")) %>%
  row_spec(nrow(dat), background = "#f2f2f2") %>%
  column_spec(ncol(dat), background = "#f2f2f2")

```

### Percent Trips by County OD: Reference

```{r Chart_Percent_Trips_By_County_OD_obs}
# Organize
dat_ref <- ref_TripTable[, .(RefTrips = sum(trips, na.rm = TRUE)), by = .(OriginCounty = OSummaryGeog, DestinationCounty = DSummaryGeog)]
dat_ref[, Reference := RefTrips/sum(RefTrips)]
dat <- add_totals(dcast.data.table(dat_ref,
                                  OriginCounty ~ DestinationCounty,
                                   fun.aggregate = sum,
                                   value.var = "Reference"))

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "tt_build_county_od_ref.csv"))
assign("db_tab_tt_build_county_od_ref", dat, envir = db_inputs)

# Table
kable(dat, escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed")) %>%
  row_spec(nrow(dat), background = "#f2f2f2") %>%
  column_spec(ncol(dat), background = "#f2f2f2")

```


### Percent Trips by County OD: Difference (Scenario - Reference)

```{r Chart_Percent_Trips_By_County_OD_diff}
# Organize
dat_diff <- merge(dat_ref, dat_scen, by = c("OriginCounty", "DestinationCounty"))
dat_diff[, Difference := Scenario - Reference]

dat <- dcast.data.table(dat_diff,
       OriginCounty ~ DestinationCounty,
       fun.aggregate = sum,
       value.var = "Difference")

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "tt_build_county_od_comp_diff.csv"))
assign("db_tab_tt_build_county_od_comp_diff", dat, envir = db_inputs)

# Table
kable(dat, escape=FALSE, digits = 3) %>%
  kable_styling(fixed_thead = TRUE, bootstrap_options = c("condensed"))

```
