---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
    css: "ReportDashboardStyles.css"
editor_options: 
  chunk_output_type: console
---

Comparison {data-navmenu="Firm Synthesis Model"}
============================================

firm_sim_taz_land_use {data-width=400 .tabset}
--------------------------------------------

**Firm Synthesis Model: Comparisons with Reference Scenario**

Firm synthesis output comparisons with reference scenario ouputs:

- firm_sim_taz_land_use processes land use inputs and prepares a database for use in later steps of the model. 
- firm_sim_scale_employees scales the synthesized establishment list to match TAZ employment totals by industry.

Scenarios being compared:

- the current scenario is **`r SCENARIO_NAME`**
- the reference scenario is **`r SCENARIO_REFERENCE_NAME`**


### firm_sim_taz_land_use: Industry

```{r Chart_firm_sim_taz_land_use_industry}

# Organize
# Current scenario
dat_scen <- melt.data.table(TAZLandUseCVTM, id.vars = c("TAZ", "Mesozone", "CountyFIPS"), variable.name = "Industry", value.name = "Employment")[!Industry %in% c("HH", "NEmp_Total")]
dat_scen[, Industry := sub("NEmp_", "", Industry)]
dat_scen <- dat_scen[, .(Employment = sum(Employment), Source = SCENARIO_NAME), keyby = Industry] 

# Reference scenario
dat_ref <- melt.data.table(ref_TAZLandUseCVTM, id.vars = c("TAZ", "Mesozone", "CountyFIPS"), variable.name = "Industry", value.name = "Employment")[!Industry %in% c("HH", "NEmp_Total")]
dat_ref[, Industry := sub("NEmp_", "", Industry)]
dat_ref <- dat_ref[, .(Employment = sum(Employment), Source = SCENARIO_REFERENCE_NAME), keyby = Industry] 

# Combine
dat <- rbind(dat_scen, dat_ref)
dat[, Source := factor(Source, levels = c(SCENARIO_REFERENCE_NAME, SCENARIO_NAME))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_taz_land_use_industry.csv"))
assign("db_tab_firm_sim_taz_land_use_industry", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "Industry", yvar = "Employment",  fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_taz_land_use_industry.png")

```

### firm_sim_taz_land_use: Employment by District

```{r Chart_firm_sim_taz_land_use_emp_District}

# Organize
# Current scenario
dat_scen <- melt.data.table(TAZLandUseCVTM, id.vars = c("TAZ", "Mesozone", "CountyFIPS"), variable.name = "Industry", value.name = "Employment")[Industry %in% c("HH", "NEmp_Total")]
dat_scen[, Industry := sub("NEmp_", "", Industry)]
dat_scen[TAZ_System, District := i.DistrictName, on = "TAZ"]
dat_scen[, TAZ_TYPE := ifelse(TAZ %in% BASE_TAZ_CMAP, "CMAP MPO Area", "Rest of Model Region")]
dat_scen <- dat_scen[, .(Employment = sum(Employment), Source = SCENARIO_NAME), keyby = .(Industry, District)] 

# Reference scenario
dat_ref <- melt.data.table(ref_TAZLandUseCVTM, id.vars = c("TAZ", "Mesozone", "CountyFIPS"), variable.name = "Industry", value.name = "Employment")[Industry %in% c("HH", "NEmp_Total")]
dat_ref[, Industry := sub("NEmp_", "", Industry)]
dat_ref[TAZ_System, District := i.DistrictName, on = "TAZ"]
dat_ref[, TAZ_TYPE := ifelse(TAZ %in% BASE_TAZ_CMAP, "CMAP MPO Area", "Rest of Model Region")]
dat_ref <- dat_ref[, .(Employment = sum(Employment), Source = SCENARIO_REFERENCE_NAME), keyby = .(Industry, District)] 

# Combine
dat <- rbind(dat_scen[Industry == "Total"], dat_ref[Industry == "Total"])
dat[, Source := factor(Source, levels = c(SCENARIO_REFERENCE_NAME, SCENARIO_NAME))]
dat[, District := factor(District, levels = levels(TAZ_System$DistrictName))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_taz_land_use_emp_district.csv"))
assign("db_tab_firm_sim_taz_land_use_emp_district", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "District", yvar = "Employment", fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_taz_land_use_emp_district.png")

```

### firm_sim_taz_land_use: Households by District

```{r Chart_firm_sim_taz_land_use_hh_district}
# Organize
# Combine
dat <- rbind(dat_scen[Industry == "HH"], dat_ref[Industry == "HH"])
dat[, Source := factor(Source, levels = c(SCENARIO_REFERENCE_NAME, SCENARIO_NAME))]
setnames(dat, c("Industry", "Employment"), c("Landuse", "Households"))
dat[, District := factor(District, levels = levels(TAZ_System$DistrictName))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_taz_land_use_hh_district.csv"))
assign("db_tab_firm_sim_taz_land_use_hh_district", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "District", yvar = "Households", fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_taz_land_use_hh_district.png")

```

firm_sim_scale_employees {data-width=400 .tabset}
--------------------------------------------

### firm_sim_scale_employees: Industry

```{r Chart_firm_sim_scale_employees_industry}
# Organize
# Current scenario
dat_scen <- ScenarioFirms[, .(Employment = sum(Employees), Source = SCENARIO_NAME), keyby = .(Industry = EmpCatGroupedName)] 

# Reference scenario
dat_ref <- ref_ScenarioFirms[, .(Employment = sum(Employees), Source = SCENARIO_REFERENCE_NAME), keyby = .(Industry = EmpCatGroupedName)] 

# Combine
dat <- rbind(dat_scen, dat_ref)
dat[, Source := factor(Source, levels = c(SCENARIO_REFERENCE_NAME, SCENARIO_NAME))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_scale_employees_industry.csv"))
assign("db_tab_firm_sim_scale_employees_industry", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "Industry", yvar = "Employment",  fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_scale_employees_industry.png")

```

### firm_sim_scale_employees: Employment by District

```{r Chart_firm_sim_scale_employees_District}
# Organize
# Current scenario
dat_scen <- ScenarioFirms[, .(Employment = sum(Employees), Source = SCENARIO_NAME), keyby = .(District = Region)] 

# Reference scenario
dat_ref <- ref_ScenarioFirms[, .(Employment = sum(Employees), Source = SCENARIO_REFERENCE_NAME), keyby = .(District = Region)] 

# Combine
dat <- rbind(dat_scen, dat_ref)
dat[, Source := factor(Source, levels = c(SCENARIO_REFERENCE_NAME, SCENARIO_NAME))]
dat[, District := factor(District, levels = levels(TAZ_System$DistrictName))]

# Save
fwrite(dat, file = file.path(SCENARIO_OUTPUT_PATH, "firm_sim_scale_employees_district.csv"))
assign("db_tab_firm_sim_scale_employees_district", dat, envir = db_inputs)

# Plot
bar_plotter(dat, xvar = "District", yvar = "Employment", fill = "Source", position = "dodge", coord_flip = TRUE, png_name = "p_firm_sim_scale_employees_district.png")

```
